codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "0...100" # 70...100

  status:
    project: true
    patch: true
    changes: false

  ignore:
    - "build/**/*"
    - "src/e2e/**/*"
    - "src/gui/tests/**/*"
    - "src/gui-qml/**/*"
    - "src/lib/src/vendor/*"
    - "src/tests/**/*"

comment:
  layout: "header, diff"
  behavior: default
