sudo: false

addons:
  apt:
    sources:
    - ubuntu-sdk-team
    packages:
    - qt5-qmake
    - qtbase5-dev
    - qtdeclarative5-dev
    - qtscript5-dev
    - qtmultimedia5-dev
    - libpulse-dev
    - qt5-default
    - qttools5-dev-tools

script:
  - qmake Grabber.pro
  - make