name: Android
on: push

jobs:
  Linux:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set environment
      run: |
        echo ::set-env name=GRABBER_VERSION::nightly
        echo ::set-env name=GRABBER_IS_NIGHTLY::1
        echo ::set-env name=PLATFORM_NAME::x64

    - name: Install packages
      run: sudo apt-get install libpulse-dev

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.12.6
        target: android
        arch: android_armv7

    - name: Create build dir
      run: mkdir build

    - name: Download Android OpenSSL libraries
      working-directory: src/cmake
      run: git clone https://github.com/KDAB/android_openssl.git

    - name: Configure
      working-directory: build
      run: |
        export ANDROID_SDK_ROOT=$ANDROID_HOME
        export ANDROID_NDK_ROOT=$ANDROID_HOME/ndk-bundle
        cmake ../src -DCMAKE_BUILD_TYPE=Release -DNIGHTLY=%GRABBER_IS_NIGHTLY% -DCOMMIT="%GITHUB_SHA%" -DVERSION="%GRABBER_VERSION%" \
          -DANDROID_ABI:STRING=armeabi-v7a \
          -DANDROID_BUILD_ABI_arm64-v8a:BOOL=OFF \
          -DANDROID_BUILD_ABI_armeabi-v7a:BOOL=ON \
          -DANDROID_BUILD_ABI_x86:BOOL=OFF \
          -DANDROID_BUILD_ABI_x86_64:BOOL=OFF \
          -DANDROID_NATIVE_API_LEVEL:STRING=21 \
          -DANDROID_NDK:PATH=$ANDROID_SDK_ROOT/ndk-bundle \
          -DANDROID_SDK:PATH=$ANDROID_SDK_ROOT \
          -DANDROID_STL:STRING=c++_shared \
          -DCMAKE_BUILD_TYPE:STRING=Debug \
          -DCMAKE_CXX_COMPILER:STRING=$ANDROID_SDK_ROOT/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ \
          -DCMAKE_C_COMPILER:STRING=$ANDROID_SDK_ROOT/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang \
          -DCMAKE_FIND_ROOT_PATH:STRING=$Qt5_DIR \
          -DCMAKE_PREFIX_PATH:STRING=$Qt5_DIR \
          -DCMAKE_TOOLCHAIN_FILE:PATH=$ANDROID_SDK_ROOT/ndk-bundle/build/cmake/android.toolchain.cmake \
          -DQT_QMAKE_EXECUTABLE:STRING=$Qt5_DIR/bin/qmake

    - name: Compile
      working-directory: build
      run: |
        cmake --build . --config Release --target sites
        cmake --build . --config Release --target gui-qml_apk
        cmake --build . --config Release --target gui_apk

    - name: Generate package
      working-directory: build
      run: |
        ls -la
        ls -la gui
        ls -la gui-qml
        ls -la gui-qml/gui-qml-armeabi-v7a
        ls -la gui-qml/gui-qml-armeabi-v7a/build
        ls -la gui-qml/gui-qml-armeabi-v7a/build/outputs
        ls -la gui-qml/gui-qml-armeabi-v7a/build/outputs/apk
        ls -la gui-qml/gui-qml-armeabi-v7a/build/outputs/apk/debug
        mv gui-qml/gui-qml-armeabi-v7a/build/outputs/apk/debug/gui-qml-armeabi-v7a-debug.apk ../Grabber-qml.apk
        mv gui/gui-armeabi-v7a/build/outputs/apk/debug/gui-armeabi-v7a-debug.apk ../Grabber.apk
        ls -la ../*.apk
