name: Linux
on: [push, pull_request]

jobs:
  Linux:
    timeout-minutes: 20
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set environment
      run: |
        echo "GRABBER_VERSION=nightly" >> $GITHUB_ENV
        echo "GRABBER_IS_NIGHTLY=1" >> $GITHUB_ENV
        echo "PLATFORM_NAME=x64" >> $GITHUB_ENV

    - name: Install packages
      run: sudo apt-get install libpulse-dev

    - name: Cache Qt
      id: cache-qt
      uses: actions/cache@v1
      with:
        path: ../Qt
        key: ${{ runner.os }}-QtCache-${{ hashFiles('.github/workflows/linux.yml') }}

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.7.2
      with:
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
        version: 5.12.6

    - name: Create build dir
      run: mkdir build

    - name: Configure
      working-directory: build
      run: cmake ../src -DCMAKE_BUILD_TYPE=Release -DNIGHTLY=$GRABBER_IS_NIGHTLY -DCOMMIT="$GITHUB_SHA" -DVERSION="$GRABBER_VERSION"

    - name: Compile
      working-directory: build
      run: |
        cmake --build . --config Release --target sites
        cmake --build . --config Release

    - name: Test
      uses: GabrielBB/xvfb-action@v1.2
      with:
        working-directory: src
        run: ../build/tests/tests

    - name: Generate package
      run: |
        ./scripts/package-linux.sh
        mv Grabber.tar.gz Grabber_nightly.tar.gz

    - name: Nightly
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: nightly-github
        name: Nightly (Github)
        allowUpdates: true
        draft: false
        prerelease: true
        artifacts: Grabber_*.tar.gz
        body: |
          Nightly automated builds from the develop branch.
          Automatically uploaded by Github actions, **use at your own risk**!

          **Head:** ${{ env.GITHUB_SHA }}
